Restructured the source code organization. Changed call to ./build_rayleigh: ./build_rayleigh --machine=Pleiades --target=all --prefix=somewhere --help

diff --git a/build_rayleigh b/build_rayleigh
--- a/build_rayleigh
+++ b/build_rayleigh
@@ -15,20 +15,103 @@
 ###  A debugging flag may be passed to makefiles that support it.
 ### ./build_rayleigh Pleiades debug  (for example)
 
-export MACHINE=$1
-export RAYLEIGH_OPT=$2
-RAYLEIGH_OPT2=$3
-RAYLEIGH_OPT3=$4
-TARGET=$2
+#!/bin/bash
+
+RAYLEIGHDIR=$PWD
+PREFIX=$RAYLEIGHDIR/bin
+MACHINE=NULL
+TARGET=all
+MACHINE_SPECIFIED=no
+NEED_HELP=no
+for option
+do
+    case $option in
+
+    -help | --help | -h)
+      NEED_HELP=yes ;;
+
+    -prefix=* | --prefix=*)
+      PREFIX=`expr "x$option" : "x-*prefix=\(.*\)"`
+      ;;
+    -machine=* | --machine=*)
+      MACHINE_SPECIFIED=yes;
+      MACHINE=`expr "x$option" : "x-*machine=\(.*\)"`
+      ;;
+    -target=* | --target=*)
+      TARGET=`expr "x$option" : "x-*target=\(.*\)"`
+      ;;
+    -*)
+      opt_error=yes;
+      echo "Invalid option: $option" >&2;
+      echo "Try ./build_rayleigh --help for usage examples." >&2;
+      #{ (exit 1); exit 1; }; }
+      ;; 
+
+    esac
+done
+
+if [[ $MACHINE_SPECIFIED == "no" && $NEED_HELP == "no" ]]; then
+  echo 'Error: must specify a machine name.' >&2;
+  echo "Try ./build_rayleigh --help for usage examples." >&2;
+  echo $NEED_HELP;
+  { ( exit 1); exit 1; };
+fi
+
+
+if [ "$NEED_HELP" == "yes" ]; then
+  echo ''
+  echo 'Usage: ./build_rayleigh --machine=MACHINE_NAME [ Options ]'
+  echo ''
+  echo 'Options: '
+  echo '  --machine         (REQUIRED) Machine name corresponding to one of the '
+  echo '                     machine files in rayleigh/src/Machinefiles'
+  echo ''
+  echo '  --target          Name of the Rayleigh target to build.  Must correspond'
+  echo '                    to one of the targets defined in the machine file.'
+  echo '                    default value : all'
+  echo ''
+  echo '  --prefix          Location in which to place the Rayleigh executables.'
+  echo '                    default value : rayleigh/bin'
+  echo ''
+  echo '  --help            Display this message.'
+  echo ''
+  echo 'Examples: '
+  echo ''
+  echo '  (1) build Rayleigh on Pleiades with avx2 optimizations:  
+                                 ./build_rayleigh machine=Pleiades target=avx2'
+  echo ''
+  echo '  (2) build Rayleigh on Pleiades with debugging flags:  
+                                 ./build_rayleigh machine=Pleiades target=dbg'
+  echo ''
+  echo '  (3) build all Rayleigh versions on Mira:  
+                                 ./build_rayleigh machine=Mira'
+  echo ''
+  echo '  (4) build all Rayleigh versions on Mira (alternate method):  
+                                 ./build_rayleigh machine=Mira target=all'
+  echo ''
+  echo '  (5) build all Rayleigh versions on Pleiades; place executable(s) in /scratch/rayleigh_exec:
+                                  ./build_rayleigh machine=Mira prefix=/scratch/rayleigh_exec' 
+  { ( exit 1); exit 1; };
+fi
+
+if [[ $MACHINE_SPECIFIED == "no" && $NEED_HELP=="yes" ]]; then
+  { ( exit 1); exit 1; };
+fi
+
+
+########################################################
+
+
 
 NOCOMM=machine.no_comments
 MACHDEF=Machine_Definitions
-if [ ! -e build ]
+BUILDDIR=src/build
+if [ ! -e $BUILDDIR ]
 then
-  mkdir build
-  cd build
+  mkdir $BUILDDIR
+  cd $BUILDDIR
 else
-  cd build
+  cd $BUILDDIR
   rm -f *.F90
   rm -f Makefile
   rm -f $MACHDEF
@@ -43,8 +126,8 @@ cp ../test_suite/*.F90 .
 cp ../physics/*.F90 .
 cp ../Utility/*.F90 .
 cp ../Utility/*.c .
-cp ../Makefiles/Makefile .
-cp ../Makefiles/object_list .
+cp ../Makefile .
+cp ../object_list .
 
 MACHINE_TYPE=Intel
 if [ $MACHINE == "Mira" ]
@@ -60,7 +143,8 @@ fi
 if [ $MACHINE_TYPE == "IBM" ] 
 then
 cp ../Utility/MakeDir.F90_IBM MakeDir.F90
-#OpenMP-related code.  Note supported presently
+# OpenMP-related code.  Not supported presently
+# Retained for future use.
 #if [ $RAYLEIGH_OPT1 == "omp" ] 
 #then
 #  echo Builing OpenMP-version-Mira
@@ -70,7 +154,7 @@ cp ../Utility/MakeDir.F90_IBM MakeDir.F90
 #fi
 fi
 
-MACHINEFILE=../Makefiles/machine.${MACHINE}
+MACHINEFILE=../Machinefiles/machine.${MACHINE}
 NOCOMM=machine.no_comments
 #First, we strip any user comments out of MACHINEFILE as we copy it to NOCOMM
 grep -o '^[^#]*' $MACHINEFILE > $NOCOMM
@@ -79,4 +163,5 @@ grep -o '^[^#]*' $MACHINEFILE > $NOCOMM
 #  This is super important as errors can arise in the make process otherwise.
 sed 's/[ \t]*$//' $NOCOMM > $MACHDEF
 echo " "
-make ${TARGET}  
+echo "PREFIX IS: "$PREFIX
+make ${TARGET}  PREFIX=${PREFIX}
